name: Continuous-Integration

on: 
    push: 
        branches: [ master ]
    pull_request: 
        branches: [ master ]

# Define a job name build 
jobs:
    build:
        # specify the runner environment
        runs-on: ubuntu-latest

        name: Deplaoying everything tp the dev cluster
        steps:
            # Deploy to the vm
          - run: | 
                echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
                chmod 700 /home/runner/ssh_key
                ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@3.104.79.165 -t "cd Brain-History/ && git pull origin master && npm install && npx tsc && pm2 restart Brainly-Dev-server"

            
